export const translations = {
  en: {
    nav: {
      home: 'Home',
      dashboard: 'Dashboard',
      marketplace: 'Marketplace',
      orders: 'Orders',
      analytics: 'Analytics',
      settings: 'Settings',
      newBatch: 'New Batch',
      login: 'Login',
      register: 'Register',
      logout: 'Logout'
    },
    home: {
      title: 'Farm to Table Traceability',
      subtitle: 'Empower small producers with digital supply chain transparency through QR-based traceability and AI-powered insights',
      getStarted: 'Get Started Free',
      goToDashboard: 'Go to Dashboard',
      whyChoose: 'Why Choose AgriSync?',
      howItWorks: 'How It Works',
      readyToTransform: 'Ready to Transform Your Supply Chain?',
      joinThousands: 'Join thousands of producers building trust and accessing premium markets',
      startFree: 'Start Free Today'
    },
    features: {
      qrTraceability: 'QR Code Traceability',
      qrDesc: 'Generate unique QR codes for each batch. Buyers can instantly verify product origin and journey.',
      trustTransparency: 'Trust & Transparency',
      trustDesc: 'Build trust with buyers through transparent supply chain records and certification tracking.',
      mobileFriendly: 'AI-Powered Mobile',
      mobileDesc: 'Works on any device with offline support, AI chat assistance for rural areas.',
      premiumMarkets: 'Premium Markets',
      premiumDesc: 'Access premium markets by proving ethical practices and sustainable farming methods.',
      smallProducers: 'Built for Small Producers',
      smallDesc: 'Designed specifically for smallholder farmers with AI guidance and minimal tech literacy.',
      globalStandards: 'Global Standards',
      globalDesc: 'Supports international certification standards and compliance requirements.'
    },
    steps: {
      step1: 'Create & Track',
      step1Desc: 'Register your harvest with AI-assisted data entry.',
      step2: 'Smart Events',
      step2Desc: 'Log processing steps with photo recognition and GPS tracking.',
      step3: 'Verify & Trust',
      step3Desc: 'Buyers scan QR codes for instant verification with trust scores.'
    },
    dashboard: {
      welcome: 'Welcome back',
      manageBatches: 'Manage your batches and track your supply chain',
      totalBatches: 'Total Batches',
      qrScans: 'QR Scans',
      recentHarvests: 'Recent Harvests',
      yourBatches: 'Your Batches',
      noBatches: 'No batches yet',
      createFirst: 'Create your first batch to start tracking your products',
      createFirstBatch: 'Create First Batch',
      viewDetails: 'View Details',
      created: 'Created',
      createNewBatch: 'Create New Batch'
    },
    batch: {
      createNew: 'Create New Batch',
      registerNew: 'Register a new product batch with AI-powered traceability',
      productName: 'Product Name',
      productType: 'Product Type',
      quantity: 'Quantity',
      unit: 'Unit',
      harvestDate: 'Harvest Date',
      location: 'Location',
      description: 'Description',
      photo: 'Product Photo (Optional)',
      cancel: 'Cancel',
      create: 'Create Batch',
      success: 'Batch created successfully!',
      selectType: 'Select type',
      fruits: 'Fruits',
      vegetables: 'Vegetables',
      grains: 'Grains',
      herbs: 'Herbs',
      dairy: 'Dairy',
      meat: 'Meat',
      processedFood: 'Processed Food',
      other: 'Other',
      aiEnhanced: 'AI-Enhanced Batch Creation'
    },
    marketplace: {
      title: 'B2B Marketplace',
      subtitle: 'Connect directly with verified producers. All products are traceable and quality-assured.',
      searchPlaceholder: 'Search products or producers...',
      allCategories: 'All Categories',
      featured: 'Featured Products',
      allProducts: 'All Products',
      addToCart: 'Add to Cart',
      available: 'available',
      trust: 'Trust',
      noProducts: 'No products found',
      adjustSearch: 'Try adjusting your search or filters',
      emptyMarketplace: 'No products in marketplace yet',
      emptyMarketplaceDesc: 'Be the first to list your products! Create a batch from your dashboard.',
      goToDashboard: 'Go to Dashboard',
      sortNewest: 'Newest First',
      sortPriceLow: 'Price: Low to High',
      sortPriceHigh: 'Price: High to Low',
      sortRating: 'Highest Rated',
      sortTrust: 'Trust Score',
      reviews: 'reviews',
      by: 'by'
    },
    orders: {
      title: 'Order Management',
      subtitle: 'Track and manage your B2B orders from buyers',
      totalOrders: 'Total Orders',
      completedRevenue: 'Completed Revenue',
      pendingRevenue: 'Pending Revenue',
      fulfillmentRate: 'Fulfillment Rate',
      allOrders: 'All Orders',
      pending: 'Pending',
      processing: 'Processing',
      shipped: 'Shipped',
      delivered: 'Delivered',
      cancelled: 'Cancelled',
      viewDetails: 'View Details',
      contactBuyer: 'Contact Buyer',
      invoice: 'Invoice',
      noOrders: 'No orders found',
      products: 'Products',
      ordered: 'Ordered',
      tracking: 'Tracking',
      estDelivery: 'Est. Delivery',
      createOrder: 'Create Order',
      createFirstOrder: 'Create your first order to start tracking sales',
      buyerName: 'Buyer Name',
      addProduct: 'Add Product',
      selectProduct: 'Select Product',
      notes: 'Notes'
    },
    analytics: {
      title: 'Analytics Dashboard',
      subtitle: 'Track your supply chain performance and buyer engagement',
      totalScans: 'Total QR Scans',
      activeBatches: 'Active Batches',
      avgTrustScore: 'Avg Trust Score',
      estRevenue: 'Est. Revenue',
      uniqueBuyers: 'Unique Buyers',
      premiumRate: 'Premium Rate',
      scansThisWeek: 'QR Scans This Week',
      topProducts: 'Top Performing Products',
      geoDistribution: 'Geographic Distribution',
      deviceBreakdown: 'Device Breakdown',
      recentActivity: 'Recent Activity',
      scans: 'scans',
      last7Days: 'Last 7 days',
      last30Days: 'Last 30 days',
      last90Days: 'Last 90 days',
      lastYear: 'Last year',
      qrScan: 'QR Scan',
      newOrder: 'New Order',
      verification: 'Verification',
      mon: 'Mon',
      tue: 'Tue',
      wed: 'Wed',
      thu: 'Thu',
      fri: 'Fri',
      sat: 'Sat',
      sun: 'Sun',
      northIndia: 'North India',
      southIndia: 'South India',
      westIndia: 'West India',
      eastIndia: 'East India',
      others: 'Others',
      mobile: 'Mobile',
      desktop: 'Desktop',
      tablet: 'Tablet'
    },
    settings: {
      title: 'Settings',
      subtitle: 'Manage your account settings and preferences',
      profile: 'Profile',
      notifications: 'Notifications',
      security: 'Security',
      appearance: 'Appearance',
      billing: 'Billing',
      apiKeys: 'API Keys',
      profileSettings: 'Profile Settings',
      changePhoto: 'Change Photo',
      username: 'Username',
      email: 'Email',
      organization: 'Organization',
      phone: 'Phone',
      bio: 'Bio',
      website: 'Website',
      theme: 'Theme',
      lightMode: 'Light Mode',
      darkMode: 'Dark Mode',
      language: 'Language',
      saveChanges: 'Save Changes',
      saved: 'Saved!',
      currentPlan: 'Current Plan',
      paymentMethod: 'Payment Method',
      twoFactor: 'Two-Factor Authentication',
      loginAlerts: 'Login Alerts',
      changePassword: 'Change Password',
      photoHint: 'JPG, PNG or GIF. Max 2MB.',
      cityCountry: 'City, Country',
      bioPlaceholder: 'Tell buyers about your farm or organization...',
      notificationPrefs: 'Notification Preferences',
      emailNotifications: 'Email Notifications',
      pushNotifications: 'Push Notifications',
      orderUpdates: 'Order Updates',
      orderUpdatesDesc: 'Receive emails when you get new orders or order status changes',
      qrScanAlerts: 'QR Scan Alerts',
      qrScanAlertsDesc: 'Get notified when your products are scanned',
      marketingTips: 'Marketing & Tips',
      marketingTipsDesc: 'Receive tips, product updates, and promotional content',
      orderAlerts: 'Order Alerts',
      orderAlertsDesc: 'Instant push notifications for new orders',
      scanNotifications: 'Scan Notifications',
      scanNotificationsDesc: 'Real-time alerts when products are verified',
      twoFactorDesc: 'Add an extra layer of security to your account',
      loginAlertsDesc: 'Get notified when someone logs into your account',
      sessionTimeout: 'Session Timeout',
      minutes: 'minutes',
      hour: 'hour',
      hours: 'hours',
      never: 'Never',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmNewPassword: 'Confirm New Password',
      updatePassword: 'Update Password',
      billingSubscription: 'Billing & Subscription',
      proPlan: 'Pro Plan',
      renewsOn: 'Renews',
      expires: 'Expires',
      update: 'Update',
      viewBillingHistory: 'View Billing History',
      apiKeysDesc: 'Use API keys to integrate AgriSync with your existing systems',
      productionKey: 'Production Key',
      testKey: 'Test Key',
      copy: 'Copy',
      generateNewKey: 'Generate New Key',
      languageChangeHint: 'The app will display in the selected language'
    },
    common: {
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      save: 'Save',
      cancel: 'Cancel',
      delete: 'Delete',
      edit: 'Edit',
      search: 'Search',
      filter: 'Filter',
      sortBy: 'Sort by',
      newest: 'Newest First',
      oldest: 'Oldest First',
      currency: '₹',
      minAgo: 'min ago',
      hourAgo: 'hour ago',
      hoursAgo: 'hours ago'
    },
    auth: {
      welcomeBack: 'Welcome Back',
      signIn: 'Sign in to your AgriSync account',
      signUp: 'Create your producer account',
      joinAgriSync: 'Join AgriSync',
      usernameOrEmail: 'Username or Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      dontHaveAccount: "Don't have an account?",
      alreadyHaveAccount: 'Already have an account?',
      signUpHere: 'Sign up here',
      signInHere: 'Sign in here',
      createAccount: 'Create Account'
    }
  },

  // Complete Hindi Translations
  hi: {
    nav: {
      home: 'होम',
      dashboard: 'डैशबोर्ड',
      marketplace: 'बाज़ार',
      orders: 'ऑर्डर',
      analytics: 'विश्लेषण',
      settings: 'सेटिंग्स',
      newBatch: 'नया बैच',
      login: 'लॉगिन',
      register: 'रजिस्टर',
      logout: 'लॉगआउट'
    },
    home: {
      title: 'खेत से मेज तक ट्रेसेबिलिटी',
      subtitle: 'QR-आधारित ट्रेसेबिलिटी और AI-संचालित अंतर्दृष्टि के माध्यम से छोटे उत्पादकों को डिजिटल आपूर्ति श्रृंखला पारदर्शिता प्रदान करें',
      getStarted: 'मुफ्त शुरू करें',
      goToDashboard: 'डैशबोर्ड पर जाएं',
      whyChoose: 'AgriSync क्यों चुनें?',
      howItWorks: 'यह कैसे काम करता है',
      readyToTransform: 'अपनी आपूर्ति श्रृंखला को बदलने के लिए तैयार हैं?',
      joinThousands: 'हजारों उत्पादकों से जुड़ें जो विश्वास बना रहे हैं और प्रीमियम बाजारों तक पहुंच रहे हैं',
      startFree: 'आज मुफ्त शुरू करें'
    },
    features: {
      qrTraceability: 'QR कोड ट्रेसेबिलिटी',
      qrDesc: 'प्रत्येक बैच के लिए अद्वितीय QR कोड बनाएं। खरीदार तुरंत उत्पाद की उत्पत्ति और यात्रा सत्यापित कर सकते हैं।',
      trustTransparency: 'विश्वास और पारदर्शिता',
      trustDesc: 'पारदर्शी आपूर्ति श्रृंखला रिकॉर्ड और प्रमाणन ट्रैकिंग के माध्यम से खरीदारों के साथ विश्वास बनाएं।',
      mobileFriendly: 'AI-संचालित मोबाइल',
      mobileDesc: 'ग्रामीण क्षेत्रों के लिए ऑफलाइन सपोर्ट और AI चैट सहायता के साथ किसी भी डिवाइस पर काम करता है।',
      premiumMarkets: 'प्रीमियम बाजार',
      premiumDesc: 'नैतिक प्रथाओं और टिकाऊ खेती विधियों को साबित करके प्रीमियम बाजारों तक पहुंचें।',
      smallProducers: 'छोटे उत्पादकों के लिए बनाया गया',
      smallDesc: 'AI मार्गदर्शन और न्यूनतम तकनीकी साक्षरता के साथ छोटे किसानों के लिए विशेष रूप से डिज़ाइन किया गया।',
      globalStandards: 'वैश्विक मानक',
      globalDesc: 'अंतर्राष्ट्रीय प्रमाणन मानकों और अनुपालन आवश्यकताओं का समर्थन करता है।'
    },
    steps: {
      step1: 'बनाएं और ट्रैक करें',
      step1Desc: 'AI-सहायता प्राप्त डेटा प्रविष्टि के साथ अपनी फसल पंजीकृत करें।',
      step2: 'स्मार्ट इवेंट्स',
      step2Desc: 'फोटो पहचान और GPS ट्रैकिंग के साथ प्रोसेसिंग चरणों को लॉग करें।',
      step3: 'सत्यापित करें और विश्वास करें',
      step3Desc: 'खरीदार ट्रस्ट स्कोर के साथ तत्काल सत्यापन के लिए QR कोड स्कैन करते हैं।'
    },
    dashboard: {
      welcome: 'वापस स्वागत है',
      manageBatches: 'अपने बैचों का प्रबंधन करें और अपनी आपूर्ति श्रृंखला को ट्रैक करें',
      totalBatches: 'कुल बैच',
      qrScans: 'QR स्कैन',
      recentHarvests: 'हाल की फसलें',
      yourBatches: 'आपके बैच',
      noBatches: 'अभी तक कोई बैच नहीं',
      createFirst: 'अपने उत्पादों को ट्रैक करना शुरू करने के लिए अपना पहला बैच बनाएं',
      createFirstBatch: 'पहला बैच बनाएं',
      viewDetails: 'विवरण देखें',
      created: 'बनाया गया',
      createNewBatch: 'नया बैच बनाएं'
    },
    batch: {
      createNew: 'नया बैच बनाएं',
      registerNew: 'AI-संचालित ट्रेसेबिलिटी के साथ एक नया उत्पाद बैच पंजीकृत करें',
      productName: 'उत्पाद का नाम',
      productType: 'उत्पाद प्रकार',
      quantity: 'मात्रा',
      unit: 'इकाई',
      harvestDate: 'फसल की तारीख',
      location: 'स्थान',
      description: 'विवरण',
      photo: 'उत्पाद फोटो (वैकल्पिक)',
      cancel: 'रद्द करें',
      create: 'बैच बनाएं',
      success: 'बैच सफलतापूर्वक बनाया गया!',
      selectType: 'प्रकार चुनें',
      fruits: 'फल',
      vegetables: 'सब्जियां',
      grains: 'अनाज',
      herbs: 'जड़ी-बूटियां',
      dairy: 'डेयरी',
      meat: 'मांस',
      processedFood: 'प्रसंस्कृत खाद्य',
      other: 'अन्य',
      aiEnhanced: 'AI-संवर्धित बैच निर्माण'
    },
    marketplace: {
      title: 'B2B बाज़ार',
      subtitle: 'सत्यापित उत्पादकों से सीधे जुड़ें। सभी उत्पाद ट्रेस करने योग्य और गुणवत्ता-आश्वासित हैं।',
      searchPlaceholder: 'उत्पाद या उत्पादक खोजें...',
      allCategories: 'सभी श्रेणियां',
      featured: 'विशेष उत्पाद',
      allProducts: 'सभी उत्पाद',
      addToCart: 'कार्ट में जोड़ें',
      available: 'उपलब्ध',
      trust: 'विश्वास',
      noProducts: 'कोई उत्पाद नहीं मिला',
      adjustSearch: 'अपनी खोज या फ़िल्टर समायोजित करें',
      emptyMarketplace: 'बाज़ार में अभी कोई उत्पाद नहीं है',
      emptyMarketplaceDesc: 'अपने उत्पाद सूचीबद्ध करने वाले पहले बनें! अपने डैशबोर्ड से एक बैच बनाएं।',
      goToDashboard: 'डैशबोर्ड पर जाएं',
      sortNewest: 'नवीनतम पहले',
      sortPriceLow: 'कीमत: कम से अधिक',
      sortPriceHigh: 'कीमत: अधिक से कम',
      sortRating: 'उच्चतम रेटिंग',
      sortTrust: 'विश्वास स्कोर',
      reviews: 'समीक्षाएं',
      by: 'द्वारा'
    },
    orders: {
      title: 'ऑर्डर प्रबंधन',
      subtitle: 'खरीदारों से अपने B2B ऑर्डर ट्रैक और प्रबंधित करें',
      totalOrders: 'कुल ऑर्डर',
      completedRevenue: 'पूर्ण राजस्व',
      pendingRevenue: 'लंबित राजस्व',
      fulfillmentRate: 'पूर्ति दर',
      allOrders: 'सभी ऑर्डर',
      pending: 'लंबित',
      processing: 'प्रोसेसिंग',
      shipped: 'भेज दिया गया',
      delivered: 'डिलीवर किया गया',
      cancelled: 'रद्द',
      viewDetails: 'विवरण देखें',
      contactBuyer: 'खरीदार से संपर्क करें',
      invoice: 'चालान',
      noOrders: 'कोई ऑर्डर नहीं मिला',
      products: 'उत्पाद',
      ordered: 'ऑर्डर किया गया',
      tracking: 'ट्रैकिंग',
      estDelivery: 'अनुमानित डिलीवरी',
      createOrder: 'ऑर्डर बनाएं',
      createFirstOrder: 'बिक्री ट्रैक करना शुरू करने के लिए अपना पहला ऑर्डर बनाएं',
      buyerName: 'खरीदार का नाम',
      addProduct: 'उत्पाद जोड़ें',
      selectProduct: 'उत्पाद चुनें',
      notes: 'नोट्स'
    },
    analytics: {
      title: 'विश्लेषण डैशबोर्ड',
      subtitle: 'अपनी आपूर्ति श्रृंखला प्रदर्शन और खरीदार जुड़ाव को ट्रैक करें',
      totalScans: 'कुल QR स्कैन',
      activeBatches: 'सक्रिय बैच',
      avgTrustScore: 'औसत विश्वास स्कोर',
      estRevenue: 'अनुमानित राजस्व',
      uniqueBuyers: 'अद्वितीय खरीदार',
      premiumRate: 'प्रीमियम दर',
      scansThisWeek: 'इस सप्ताह QR स्कैन',
      topProducts: 'शीर्ष प्रदर्शन करने वाले उत्पाद',
      geoDistribution: 'भौगोलिक वितरण',
      deviceBreakdown: 'डिवाइस विश्लेषण',
      recentActivity: 'हाल की गतिविधि',
      scans: 'स्कैन',
      last7Days: 'पिछले 7 दिन',
      last30Days: 'पिछले 30 दिन',
      last90Days: 'पिछले 90 दिन',
      lastYear: 'पिछला वर्ष',
      qrScan: 'QR स्कैन',
      newOrder: 'नया ऑर्डर',
      verification: 'सत्यापन',
      mon: 'सोम',
      tue: 'मंगल',
      wed: 'बुध',
      thu: 'गुरु',
      fri: 'शुक्र',
      sat: 'शनि',
      sun: 'रवि',
      northIndia: 'उत्तर भारत',
      southIndia: 'दक्षिण भारत',
      westIndia: 'पश्चिम भारत',
      eastIndia: 'पूर्व भारत',
      others: 'अन्य',
      mobile: 'मोबाइल',
      desktop: 'डेस्कटॉप',
      tablet: 'टैबलेट'
    },
    settings: {
      title: 'सेटिंग्स',
      subtitle: 'अपनी खाता सेटिंग्स और प्राथमिकताएं प्रबंधित करें',
      profile: 'प्रोफ़ाइल',
      notifications: 'सूचनाएं',
      security: 'सुरक्षा',
      appearance: 'दिखावट',
      billing: 'बिलिंग',
      apiKeys: 'API कुंजियां',
      profileSettings: 'प्रोफ़ाइल सेटिंग्स',
      changePhoto: 'फोटो बदलें',
      username: 'उपयोगकर्ता नाम',
      email: 'ईमेल',
      organization: 'संगठन',
      phone: 'फोन',
      bio: 'परिचय',
      website: 'वेबसाइट',
      theme: 'थीम',
      lightMode: 'लाइट मोड',
      darkMode: 'डार्क मोड',
      language: 'भाषा',
      saveChanges: 'परिवर्तन सहेजें',
      saved: 'सहेजा गया!',
      currentPlan: 'वर्तमान योजना',
      paymentMethod: 'भुगतान विधि',
      twoFactor: 'दो-कारक प्रमाणीकरण',
      loginAlerts: 'लॉगिन अलर्ट',
      changePassword: 'पासवर्ड बदलें',
      photoHint: 'JPG, PNG या GIF. अधिकतम 2MB.',
      cityCountry: 'शहर, देश',
      bioPlaceholder: 'खरीदारों को अपने फार्म या संगठन के बारे में बताएं...',
      notificationPrefs: 'सूचना प्राथमिकताएं',
      emailNotifications: 'ईमेल सूचनाएं',
      pushNotifications: 'पुश सूचनाएं',
      orderUpdates: 'ऑर्डर अपडेट',
      orderUpdatesDesc: 'नए ऑर्डर या ऑर्डर स्थिति बदलने पर ईमेल प्राप्त करें',
      qrScanAlerts: 'QR स्कैन अलर्ट',
      qrScanAlertsDesc: 'जब आपके उत्पाद स्कैन किए जाएं तो सूचना प्राप्त करें',
      marketingTips: 'मार्केटिंग और टिप्स',
      marketingTipsDesc: 'टिप्स, उत्पाद अपडेट और प्रचार सामग्री प्राप्त करें',
      orderAlerts: 'ऑर्डर अलर्ट',
      orderAlertsDesc: 'नए ऑर्डर के लिए तत्काल पुश सूचनाएं',
      scanNotifications: 'स्कैन सूचनाएं',
      scanNotificationsDesc: 'उत्पाद सत्यापित होने पर रीयल-टाइम अलर्ट',
      twoFactorDesc: 'अपने खाते में सुरक्षा की एक अतिरिक्त परत जोड़ें',
      loginAlertsDesc: 'जब कोई आपके खाते में लॉगिन करे तो सूचना प्राप्त करें',
      sessionTimeout: 'सत्र समय सीमा',
      minutes: 'मिनट',
      hour: 'घंटा',
      hours: 'घंटे',
      never: 'कभी नहीं',
      currentPassword: 'वर्तमान पासवर्ड',
      newPassword: 'नया पासवर्ड',
      confirmNewPassword: 'नया पासवर्ड पुष्टि करें',
      updatePassword: 'पासवर्ड अपडेट करें',
      billingSubscription: 'बिलिंग और सदस्यता',
      proPlan: 'प्रो प्लान',
      renewsOn: 'नवीनीकरण',
      expires: 'समाप्ति',
      update: 'अपडेट',
      viewBillingHistory: 'बिलिंग इतिहास देखें',
      apiKeysDesc: 'AgriSync को अपने मौजूदा सिस्टम के साथ एकीकृत करने के लिए API कुंजियों का उपयोग करें',
      productionKey: 'प्रोडक्शन कुंजी',
      testKey: 'टेस्ट कुंजी',
      copy: 'कॉपी',
      generateNewKey: 'नई कुंजी बनाएं',
      languageChangeHint: 'भाषा बदलने के बाद पूरा ऐप चयनित भाषा में दिखेगा'
    },
    common: {
      loading: 'लोड हो रहा है...',
      error: 'त्रुटि',
      success: 'सफल',
      save: 'सहेजें',
      cancel: 'रद्द करें',
      delete: 'हटाएं',
      edit: 'संपादित करें',
      search: 'खोजें',
      filter: 'फ़िल्टर',
      sortBy: 'क्रमबद्ध करें',
      newest: 'नवीनतम पहले',
      oldest: 'पुराना पहले',
      currency: '₹',
      minAgo: 'मिनट पहले',
      hourAgo: 'घंटा पहले',
      hoursAgo: 'घंटे पहले'
    },
    auth: {
      welcomeBack: 'वापस स्वागत है',
      signIn: 'अपने AgriSync खाते में साइन इन करें',
      signUp: 'अपना उत्पादक खाता बनाएं',
      joinAgriSync: 'AgriSync से जुड़ें',
      usernameOrEmail: 'उपयोगकर्ता नाम या ईमेल',
      password: 'पासवर्ड',
      confirmPassword: 'पासवर्ड की पुष्टि करें',
      dontHaveAccount: 'खाता नहीं है?',
      alreadyHaveAccount: 'पहले से खाता है?',
      signUpHere: 'यहां साइन अप करें',
      signInHere: 'यहां साइन इन करें',
      createAccount: 'खाता बनाएं'
    }
  }
};
